name: CI/CD - Build & Deploy to EKS

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: appointment-service
  CLUSTER_NAME: demo-eks-cluster

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    # 1️⃣ Checkout Repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # 2️⃣ Configure AWS Credentials
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    # 3️⃣ Login to Amazon ECR
    - name: Login to Amazon ECR
      run: |
        aws ecr get-login-password --region $AWS_REGION \
        | docker login --username AWS --password-stdin \
        ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.$AWS_REGION.amazonaws.com

    # 4️⃣ Build Docker Image
    - name: Build Docker Image
      run: |
        IMAGE_TAG=$(echo $GITHUB_SHA | cut -c1-7)
        ECR_URI=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY

        docker build -t $ECR_REPOSITORY:$IMAGE_TAG .
        docker tag $ECR_REPOSITORY:$IMAGE_TAG $ECR_URI:$IMAGE_TAG
        docker tag $ECR_REPOSITORY:$IMAGE_TAG $ECR_URI:latest

    # 5️⃣ Push Docker Image
    - name: Push Docker Image
      run: |
        IMAGE_TAG=$(echo $GITHUB_SHA | cut -c1-7)
        ECR_URI=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY

        docker push $ECR_URI:$IMAGE_TAG
        docker push $ECR_URI:latest

    # 6️⃣ Update kubeconfig for EKS
    - name: Update kubeconfig
      run: |
        aws eks update-kubeconfig \
          --region $AWS_REGION \
          --name $CLUSTER_NAME

    # 7️⃣ Deploy to EKS
    - name: Deploy to EKS
      run: |
        IMAGE_TAG=$(echo $GITHUB_SHA | cut -c1-7)
        ECR_URI=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY

        # First time deployment
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml

        # Update image for rolling deployment
        kubectl set image deployment/appointment-service \
        appointment-service=$ECR_URI:$IMAGE_TAG --record

        # Wait for rollout
        kubectl rollout status deployment/appointment-service
